config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "cats#index"

  resources :cats, except: :destroy do
    resources :cat_rental_requests, only: [:new]
  end
  resources :cat_rental_requests, only: [:new, :create] do
    member do
      post :approve
      post :deny
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint           not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
require 'action_view'

class Cat < ApplicationRecord
  include ActionView::Helpers::DateHelper

  # .freeze renders a constant immutable.
  CAT_COLORS = %w[black white orange brown].freeze

  validates :color, inclusion: CAT_COLORS
  validates :sex, inclusion: %w[M F]
  # Note that you don't need to validate `color` or `sex` for presence because
  # NULL values for those columns will fail the inclusion tests.
  validates :birth_date, :name, presence: true
  validate :birth_date_cannot_be_future

  # Remember: `has_many` is just a method where the first argument is the name
  # of the association and the second argument is an options hash.
  has_many :rental_requests,
    class_name: :CatRentalRequest,
    dependent: :destroy

  def birth_date_cannot_be_future
    # Must check that birth_date is present because `>` will crash if run on
    # `nil`
    return unless birth_date.present? && birth_date > Date.today

    errors.add(:birth_date, "can't be in the future")
  end

  def age
    time_ago_in_words(birth_date)
  end
end

app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :bigint           not null, primary key
#  cat_id     :bigint           not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           default("PENDING"), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class CatRentalRequest < ApplicationRecord
  # .freeze renders constants immutable
  STATUS_STATES = %w[APPROVED DENIED PENDING].freeze

  validates :status, inclusion: STATUS_STATES
  # The `presence` of `status` is guaranteed if it is included in
  # `STATUS_STATES`; no need to check for it again
  validates :end_date, :start_date, presence: true
  validate :start_must_come_before_end
  validate :does_not_overlap_approved_request

  belongs_to :cat

  after_initialize :assign_pending_status

  def approve!
    raise 'not pending' unless self.status == 'PENDING'

    transaction do
      self.status = 'APPROVED'
      self.save!

      # When you approve this request, you reject all other overlapping
      # requests for this cat.
      overlapping_pending_requests.each do |req|
        req.update!(status: 'DENIED')
      end
    end
  end

  def approved?
    self.status == 'APPROVED'
  end

  def denied?
    self.status == 'DENIED'
  end

  def deny!
    self.status = 'DENIED'
    self.save!
  end

  def pending?
    self.status == 'PENDING'
  end

  private

  def assign_pending_status
    self.status ||= 'PENDING'
  end

  def overlapping_requests
    # ==========================================================================
    #
    # Ranges can overlap in several ways:
    #
    #   |-----|       |-----|     |---|
    #       |-----|   |-----|   |-------|
    #     (2x)                    (2x)
    #
    # ==========================================================================
    #
    # However, it is easier to think of the two cases where they do not overlap:
    #
    #    [Case 1]
    #
    #        A              B
    #    |-------|      |-------|
    #    A(s)    A(e)   B(s)    B(e)
    #
    # The start point of B comes after the end point of A. Thus: B(s) > A(e)
    #
    #
    #    [Case 2]
    #
    #        B              A
    #    |-------|      |-------|
    #    B(s)    B(e)   A(s)    A(e)
    #
    # The start point of A comes after the end point of B. Thus: A(s) > B(e)
    #
    # ==========================================================================
    #
    # Taking those two cases, you can say there's no overlap when:
    #
    #   B(s) > A(e) || A(s) > B(e)
    #
    # ==========================================================================
    #
    # You can negate this to get all cases where there must be overlap:
    #
    #   !( B(s) > A(e) || A(s) > B(e) )
    #
    # In order for overlap to occur, the other range cannot be entirely before
    # it or entirely after it.
    #
    # ==========================================================================
    #
    # You could distribute the negation:
    #
    #   !( B(s) > A(e) ) && !( A(s) > B(e) )
    #
    # And take it even further, making it shorter, but perhaps less intuitive:
    #
    #   B(s) <= A(e) && A(s) <= B(e)
    #
    # ==========================================================================

    # You want:
    # 1. A different request
    # 2. That is for the same cat.
    # 3. That overlaps.

    CatRentalRequest
      .where.not(id: self.id)
      .where(cat_id: cat_id)
      .where.not('start_date > :end_date OR end_date < :start_date',
                 start_date: start_date, end_date: end_date)
  end

  def overlapping_approved_requests
    overlapping_requests.where('status = \'APPROVED\'')
  end

  def overlapping_pending_requests
    overlapping_requests.where('status = \'PENDING\'')
  end

  def does_not_overlap_approved_request
    # A denied request doesn't need to be checked. A pending request
    # should be checked; users shouldn't be able to make requests for
    # periods during which a cat has already been spoken for.
    return if self.denied? || overlapping_approved_requests.empty?

    errors.add(:base, 'Request conflicts with existing approved request')
  end

  def start_must_come_before_end
    return if start_date < end_date

    errors.add(:start_date, 'must come before end date')
    errors.add(:end_date, 'must come after start date')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def approve
    current_cat_rental_request.approve!
    redirect_to cat_url(current_cat)
  end

  def create
    @rental_request = CatRentalRequest.new(cat_rental_request_params)
    if @rental_request.save
      redirect_to cat_url(@rental_request.cat)
    else
      flash.now[:errors] = @rental_request.errors.full_messages
      render :new
    end
  end

  def deny
    current_cat_rental_request.deny!
    redirect_to cat_url(current_cat)
  end

  def new
    @rental_request = CatRentalRequest.new
    # Grab the cat_id from params if it exists. 
    # If it doesn't exist, :cat_id will still be nil.
    @rental_request.cat_id = params[:cat_id] 
  end

  private

  def current_cat_rental_request
    @rental_request ||=
      CatRentalRequest.includes(:cat).find(params[:id])
  end

  def current_cat
    current_cat_rental_request.cat
  end

  def cat_rental_request_params
    params.require(:cat_rental_request).permit(:cat_id, :end_date, :start_date, :status)
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :new
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :edit
    end
  end

  private

  def cat_params
    params.require(:cat).permit(:birth_date, :color, :description, :name, :sex)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cat_rental_requests/new.html.erb
<section class="page"><div class="centered-box">
  <h1>Create Rental Request</h1>

  <%= render "shared/errors" %>

  <form action="<%= cat_rental_requests_url %>" method="post">
    <label for="cat_rental_request_cat_id">Cat</label>
    <select name="cat_rental_request[cat_id]"
            id="cat_rental_request_cat_id"
            required>
      <option selected disabled>--Select Cat--</option>
      <% Cat.all.each do |cat| %>
        <% selected = @rental_request.cat_id == cat.id %>
        <option <%= selected ? "selected" : "" %>
                value="<%= cat.id %>">
          <%= cat.name %>
        </option>
      <% end %>
    </select>
    <br>

    <label for="cat_rental_request_start_date">Start Date</label>
    <input
      type="date"
      name="cat_rental_request[start_date]"
      value="<%= @rental_request.start_date %>"
      id="cat_rental_request_start_date"
      required>
    <br>

    <label for="cat_rental_request_end_date">End Date</label>
    <input
      type="date"
      name="cat_rental_request[end_date]"
      value="<%= @rental_request.end_date %>"
      id="cat_rental_request_end_date"
      required>
    <br>

    <input type="submit">
  </form>
</div></section>

app/views/cats/_form.html.erb
<% action = (cat.persisted? ? cat_url(cat) : cats_url) %>
<% method = (cat.persisted? ? :PATCH : :POST) %>

<form action="<%= action %>" method="POST">
  <input type="hidden" name="_method" value="<%= method %>">

  <label for="cat_name">Name</label>
  <input
    type="text"
    name="cat[name]"
    id="cat_name"
    value="<%= cat.name %>"
  >
  <br>

  <label for="cat_birth_date">Birth date</label>
  <input
    type="date"
    name="cat[birth_date]"
    id="cat_birth_date"
    value="<%= cat.birth_date %>"
  >
  <br>

  <label for="cat_color">Color</label>
  <select name="cat[color]" id="cat_color">
    <option disabled selected>-- select a color --</option>
      <% Cat::CAT_COLORS.each do |color| %>
        <option
          <%= cat.color == color ? "selected" : "" %>
          value="<%= color %>">
          <%= color.upcase %>
        </option>
      <% end %>
  </select>
  <br>

  <input
    type="radio"
    name="cat[sex]"
    value="M"
    id="cat_sex_male"
    <%= cat.sex == "M" ? "checked" : "" %>
  >
  <label for="cat_sex_male">Male</label>
  <input
    type="radio"
    name="cat[sex]"
    value="F"
    id="cat_sex_female"
    <%= cat.sex == "F" ? "checked" : "" %>
  >
  <label for="cat_sex_female">Female</label>
  <br>

  <label>
    Description
    <textarea name="cat[description]"><%= cat.description %></textarea>
  </label>

  <br>
  <% submit_text = (cat.persisted? ? 'Update' : 'Create') + ' cat!' %>
  <input type="submit" value="<%= submit_text %>">
</form>

app/views/cats/_req_tr.html.erb
<tr>
  <td><%= req.start_date %></td>
  <td><%= req.end_date %></td>
  <td>
    <% if req.pending? %>
        <form action="<%= approve_cat_rental_request_url(req) %>" method="post">
          <input type="submit" value="Approve">
        </form>
        <form action="<%= deny_cat_rental_request_url(req) %>" method="post">
          <input type="submit" value="Deny">
        </form>
    <% else %>
      <%= req.status %>
    <% end %>
  </td>
</tr>

app/views/cats/edit.html.erb
<section class="page"><div class="centered-box">
  <h1>Edit My Cat</h1>
  <%= render 'shared/errors' %>
  <%= render 'form', cat: @cat %>
</div></section>

app/views/cats/index.html.erb
<%# Code before bonus styling added. (Closing '% >' all have extra space added
to allow commenting to continue.)

  <h1>Cats upon cats!</h1>

  <ul>
    <% @cats.each do |cat| % >
      <li><a href="<%= cat_url(cat) % >"><%= cat.name % ></a></li>
    <% end % >
  </ul>

  <a href="<%= new_cat_url % >">Create cat</a>
%>

<section class="cat-index-holder">
  <nav>
    <h1>ALL THE CATS IN THE WORLD</h1>
    <a href="<%= new_cat_url %>">
      Add Cat
      <i class="fa fa-plus" aria-hidden="true"></i>
    </a>
    <a href="<%= new_cat_rental_request_url %>">
      Request a Rental
      <i class="fa fa-plus" aria-hidden="true"></i>
    </a>
  </nav>
  <section class="cat-index">
    <% @cats.each do |cat| %>
      <div class="cat-index-item">
        <div>
          <img src="http://placekitten.com/g/231/231" >
          <br /><a href="<%= cat_url(cat) %>">Rent <%= cat.name %></a>
        </div>
      </div>
    <% end %>
  </section>
</section>

app/views/cats/new.html.erb
<section class="page"><div class="centered-box">
  <h1>New Cat</h1>
  <%= render 'shared/errors' %>
  <%= render 'form', cat: @cat %>
</div></section>

app/views/cats/show.html.erb
<section class="page"><div class="centered-box">
  <img src="http://placekitten.com/g/300/300" >
  <h1><%= @cat.name %></h1>

  <table>
    <tr>
      <th>Attribute</th>
      <th>Value</th>
    </tr>
    <% [:age, :birth_date, :color, :sex].each do |attr_name| %>
      <tr>
        <td><%= attr_name %></td>
        <td><%= @cat.send(attr_name) %></td>
      </tr>
    <% end %>
    <% if @cat.description.present? %>
      <tr>
        <th colspan="2">Description</th>
      </tr>
      <tr>
        <td colspan="2"><%= @cat.description %></td>
      </tr>
    <% end %>
  </table>

  <a href="<%= edit_cat_url(@cat) %>">Edit <%= @cat.name %></a>

  <br><br>
  <h1>Rental Requests</h1>
  <% if @cat.rental_requests.empty? %>
    <p><%= @cat.name %> has no rental requests.</p>
  <% else %>
    <table>
      <tr>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Status</th>
      </tr>
      <% @cat.rental_requests.order('start_date').each do |req| %>
        <%= render 'req_tr', req: req %>
      <% end %>
    </table>
  <% end %>
  <a href="<%= new_cat_cat_rental_request_url(@cat) %>">
    Request a Rental
  </a>
</div></section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>99 Cats</title>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC:400,700" rel="stylesheet">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <nav class="main-nav">
      <h1><a href="<%= cats_url %>">99 Cats</a></h1>
    </nav>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <ul>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
<% end %>